versions:
  - ver: 'v0.1'
    repos:
        - name: api
          url: https://github.com/atomix/api
          tagName: master
        - name: controller
          url: https://github.com/atomix/kubernetes-controller
          tagName: master
        - name: go-client
          url: https://github.com/atomix/go-client
          tagName: master
        - name: java-client
          url: https://github.com/atomix/java-client
          tagName: master
        - name: go-framework
          url: https://github.com/atomix/go-framework
          tagName: master
        - name: raft-replica
          url: https://github.com/atomix/raft-replica
          tagName: master
        - name: cli
          url: https://github.com/atomix/cli
          tagName: master
        - name: tests
          url: https://github.com/atomix/kubernetes-tests
          tagName: master
        - name: benchmarks
          url: https://github.com/atomix/kubernetes-benchmarks
          tagName: master

LatestVersion: "v0.1"
