copyright: 2020 Open Networking Foundation
dev_addr: 0.0.0.0:8000
docs_dir: content
edit_uri: ""
extra:
  social:
  - link: https://github.com/atomix
    type: github
extra_css:
- styles/css/extra.css
- theme/css/atomix-menu.css
- theme/css/atomix-menu.css
extra_javascript:
- theme/js/atomix-menu.js
- theme/js/atomix-menu.js
markdown_extensions:
- attr_list
- codehilite
- admonition
- footnotes
nav: null
plugins:
- search
- minify:
    minify_html: true
repo_name: Atomix
repo_url: https://github.com/atomix
site_author: Atomix Cloud
site_description: Atomix Cloud
site_name: Atomix Cloud
site_url: ""
theme:
  custom_dir: theme
  feature:
    tabs: false
  i18n:
    next: Next
    prev: Previous
  include_sidebar: true
  language: en
  logo: images/atomix-logo.png
  name: material
  palette:
    accent: teal
    primary: teal
